var LOCALE_charmsbar = [
    "",
    "Поиск",
    "Поделится",
    "Пуск",
    "Устройства",
    "Параметры",
    "Параметры",
    "Изменение параметров компьютера",
    "Сеть",
    "Звук",
    "Яркость",
    "Уведомления",
    "Выключение",
    "Клавиатура",
    "Персонализация",
    "О программе",
    "О программе",
    "Поиск",
    `<h1>Эта функция пока не доступна</h1><p>В данной версии Okna8 эта функция не реализована.</p><div class="buttons"><button style="margin-right: 0;" onclick='CloseMetroDialog("__ID__")'>Отмена</button></div>`,
    `<p>Возможно, это приложение не локализовано на ваш язык</p><div class="buttons"><button style="margin-right: 0;" onclick='CloseMetroDialog("__ID__")'>Закрыть</button></div>`,
    "Цвет фона",
    "Цветовая тема",
    "Доступна новая версия Okna8",
    "Вы используете версию ",
    ". Доступна более новая версия - ",
    "Скачать",
    "Позже",
    "Доступна новая версия Okna8",
    "Назмите здесь, чтобы скачать обновление",
    "Назмите здесь, чтобы установить обновление",
    `<h1>Создание учётной записи</h1><p>Введите имя, под которым будет входить пользователь компьютера в свою учётную запись.</p><input type="text" id="OchenKrutoyInputHaha" placeholder="Например: Игорь"><div class="buttons" style="margin-top:60px"><button onclick='if($("#OchenKrutoyInputHaha").val() != ""){CreateUser($("#OchenKrutoyInputHaha").val());CloseMetroDialog("__ID__");setTimeout(()=>{shutdown(\`l\`)},100)}'>Далее</button><button onclick='CloseMetroDialog("__ID__")' style="margin-right: 0;">Отмена</button></div>`,
    'Обновить',
    'Обновление готово к установке',
    'Нажмите здесь, чтобы установить обновление'
]