var LOCALE_oobe = [
    "",
    "Setup basic settings",
    "Personalize",
    "Network",
    "Settings",
    "Login",
    "Personalize",
    "This english localization is temporary. After some time, it will be replaced by a more perfect one.",
    "PC name",
    "For example: home-pc",
    "Next",
    "Settings",
    "Standart settings",
    "We recommend that you use these settings (if you select them, your computer will sometimes send data to Microsoft). You can configure them now or later.",
    "<li>Автоматически находить компьютеры и устройства в этой сети и подключаться к ним.</li><li>Автоматически устанавливать обновления Windows и приложений, а также программное обеспечение для устройств.</li><li>Включить заголовок Do Not Track (\"Не отслеживать\") в Internet Explorer.</li><li>Защищать компьютер от небезопасных файлов, приложений и веб-сайтов, а также искать решения проблем в Интернете.</li><li>Отправлять в Майкрософт данные для улучшения работы программного обеспечения, служб и услуг определения местоположения.</li><li>Получать варианты и результаты поиска из Интернета с помощью Bing и Windows Search и разрешить Майкрософт использовать сведения о вашем расположении и другие данные для персонализции результатов.</li><li>Предварительно загружать прогнозируемые страницы в Internet Explorer (для этого ваш журнал браузера будет отправляться в Майкрософт).</li><li>Разрешить Windows и приложениям использовать ваше имя, аватар и идентификатор получателя рекламы, а также запрашивать сведения о вашем местонахождении у платформы расположений Windows.</li>",
    "Use standart settings",
    "Edit settings",
    "Your account",
    "If you want to use a password, select a one, then you can remember, but others - hard to hack.",
    "For example: Igor",
    "User name",
    "Password",
    "Re-enter password",
    "Password hint",
    "Finish",
    "Completing setup"
]