var LOCALE_charmsbar = [
    "",
    "Пошук",
    "Поділитися",
    "Пуск",
    "Пристрої",
    "Параметри",
    "Параметри",
    "Зміна параметрів комп'ютера",
    "Мережа",
    "Звук",
    "Яскравість",
    "Повідомлення",
    "Вимкнення",
    "Клавіатура",
    "Персоналізація",
    "Про програму",
    "Про програму",
    "Пошук",
    `<h1>Ця функція поки не доступна</h1><p>У цій версії Okna8 ця функція не реалізована.</p><div class="buttons"><button style="margin- right: 0;" onclick='CloseMetroDialog("__ID__")'>Скасувати</button></div>`,
    `<p>Можливо, ця програма не локалізована на вашу мову</p><div class="buttons"><button style="margin-right: 0;" onclick='CloseMetroDialog("__ID__")'>Закрити</button></div>`,
    "Background color",
    "Accent color",
    "Доступна нова версія Okna8",
    "Ви використовуєте версію",
    ". Доступна нова версія - ",
    "Завантажити",
    "Пізніше",
    "Доступна нова версія Okna8",
    "Назміть тут, щоб завантажити оновлення",
    "Назвіть тут, щоб встановити оновлення",
    `<h1>Создание учётной записи</h1><p>Введите имя, под которым будет входить пользователь компьютера в свою учётную запись.</p><input type="text" id="OchenKrutoyInputHaha" placeholder="Например: Игорь"><div class="buttons" style="margin-top:60px"><button onclick='if($("#OchenKrutoyInputHaha").val() != ""){CreateUser($("#OchenKrutoyInputHaha").val());CloseMetroDialog("__ID__");setTimeout(()=>{shutdown(\`l\`)},100)}'>Далее</button><button onclick='CloseMetroDialog("__ID__")' style="margin-right: 0;">Отмена</button></div>`,
    'Update now',
    'Обновление готово к установке',
    'Нажмите здесь, чтобы установить обновление'
]