LOCALE_cpl_taskbarProperties = [
    '',
    'Taskbar properties',
    'Taskbar',
    'Navigation',
    'Jump lists',
    'Toolboxes',
    'Pin taskbar',
    'Automatticly hide taskbar',
    'Use small buttons on taskbar',
    'Bottom',
    'Left',
    'Right',
    'Top',
    'Taskbar location:',
    'Always group, hide labels',
    'Group when taskbar full',
    'Not group',
    'Taskbar buttons:',
    'Setting...',
    'Notification area:',
    'Show Windows Store apps on taskbar',
    'Show desktop when I hover pointer to "Minimize all windows" on taskbar',
    'How to setting taskbar?',
]